# Generated by Django 3.2.11 on 2022-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilnote1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshortcut',
            name='page_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myshortcut',
            name='team_member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myshortcut',
            name='image',
            field=models.ImageField(blank=True, upload_to='skilnote1/%y%m%d'),
        ),
    ]
