# Generated by Django 3.2.8 on 2021-10-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0002_profile_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
